sudo: false
language: ruby
rvm:
  - 2.0.0
before_install:
- travis_retry gem install jekyll
- travis_retry gem install kramdown
- npm install -g netlify
script:
- jekyll build --safe
- "find ./ -type d -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
