sudo: required
language: ruby
rvm:
  - 2.0.0
before_install:
- travis_retry gem install jekyll
- travis_retry gem install kramdown
- travis_retry sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
- travis_retry sudo apt-get update
- travis_retry sudo apt-get install tree -y
script:
- jekyll build --safe
- tree _site
notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
